populating colours from hexa-decimal value's
yellowmessenger/ymchat-xamarin pull request #9
Opened 2022-02-04 11:29 UTC by PurushYM

- statusBarcolorFromHex
- closeButtonColorFromHex

2022-02-04 11:34 UTC, kaunteya requested changes

2022-02-04 11:34 UTC, kaunteya commented on YmChat/YmChat.apple.cs
> +                    }
We can consider only 6 letter hex format #123456. Let's skip 3 character format

2022-02-04 11:40 UTC, PurushYM commented on YmChat/YmChat.apple.cs
> +                    }
ok

2022-02-07 05:11 UTC, kaunteya approved these changes
iOS part looks good

2022-02-07 06:39 UTC, sukrit-ym requested changes

2022-02-07 06:39 UTC, sukrit-ym commented on YmChat.nuspec
> +    <releaseNotes>Added setCustomLoaderURL API (for setting custom loading image for chatbot)</releaseNotes>
update the message with StatusBarColor and CloseButtonColor API

2022-02-07 06:39 UTC, sukrit-ym commented on YmChat/YmChat.apple.cs
> +
Why is this required?

2022-02-07 06:41 UTC, PurushYM commented on YmChat/YmChat.apple.cs
> +
For changing Hex color to iOS UI color

2022-02-07 06:49 UTC, sukrit-ym commented on YmChat.nuspec
> +    <releaseNotes>Added API's for setting color tp statusbar and clpseButton </releaseNotes>
Please correct the spellings

2022-02-07 06:49 UTC, sukrit-ym commented on YmChat.nuspec
> +    <releaseNotes>Added API's for setting color tp statusbar and clpseButton </releaseNotes>
Message - " Added API's for custom bot loader using a url, setting color of status bar and close button with hexadecimal color value."

2022-02-07 08:53 UTC, sukrit-ym approved these changes

2022-02-07 08:54 UTC, merged